#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use Jinas\BMLConsole\Helpers\BML;

require 'vendor/autoload.php';

$command = new Jinas\BMLConsole\InitCommand(new BML);
$app = new Application('Bml Console', '0.1');
$app->add($command);
$app->setDefaultCommand($command->getName());
$app->run();
