#! /usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}


$command = new Jinas\BMLConsole\InitCommand(new \Jinas\BMLConsole\Helpers\BML);
$app = new Symfony\Component\Console\Application('Bml Console', '0.2');
$app->add($command);
$app->setDefaultCommand($command->getName());
$app->run();
